kakPewe4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls'), name ='story3'),
    path('story1/', include('story1.urls'), name = 'story1'),
    path('story4/', include('story4.urls'), name = 'story4'),
    path('story6/', include('story6.urls'), name = 'story6'),
    path('story7/', include('story7.urls'), name = 'story7'),
    path('story8/', include('story8.urls'), name = 'story8'),
    path('story9/', include('story9.urls'), name = 'story9'),

]

story1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/<str:data>', views.search, name='search'),
    path('search/', views.search, name='search'),
]

story8/models.py
from django.db import models

# Create your models here.

story8/views.py
from django.shortcuts import render
import requests
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

def index(request):
    return render(request, "index_story8.html")


def search(request, data):
    return JsonResponse(requests.get('https://www.googleapis.com/books/v1/volumes?q='+ data).json())

story8/templates/index_story8.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<div class="fluid-container" style="margin: 10%;">
    <form method="POST" class = "search">
        {% csrf_token %}
        <input class="form-control" type="text" placeholder="Search" aria-label="Search" name = "search" id = "search">
        <button type="submit" class="btn btn-default">SEARCH</button>
    </form>
    &nbsp;
    <div class = "row" id = "result">

    </div>
</div>
<script>
    $(".search").submit(function () {
      event.preventDefault();
      $ ( "#result" ).empty();
      var search = $( "#search" ).val();
      $.ajax({
        url: "{% url 'story8:search' %}" +search ,
        data: {
          'data': search,
          'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        method: "POST",
        dataType: 'json',
        success: function (data) {
          $( data.items ).each(function(index, element){
            $ ( "#result" ).append("<div class = 'col-md-4'></div>")
            var current = $ ( '#result' ).children().last()
            $ ( current ).append("<div class = 'panel panel-default'></div>")
            current =  $ ( ".panel" ).last()
            $ ( current ).append("<div class = 'panel-heading'>" +element.volumeInfo.title +"</div>")
            $ ( current ).append("<div class = 'panel-body'></div>")
            current =  $ ( ".panel-body" ).last()
            $ ( current ).append("<img src ='" + element.volumeInfo.imageLinks.thumbnail + "'>")
            $ ( current ).append("<h3>Deskripsi</h3>")
            $ ( current ).append("<p>" + element.volumeInfo.description + "</p>")
          });
          }
        });
      });

</script>
{% endblock content %}