kakPewe4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls'), name ='story3'),
    path('story1/', include('story1.urls'), name = 'story1'),
    path('story4/', include('story4.urls'), name = 'story4'),
    path('story6/', include('story6.urls'), name = 'story6'),
    path('story7/', include('story7.urls'), name = 'story7'),
    path('story8/', include('story8.urls'), name = 'story8'),
    path('story9/', include('story9.urls'), name = 'story9'),

]

story1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.event, name='home'),
    path('add/<int:id_number>', views.add, name='add'),
    path('new_event/',views.new_event, name ='add_event')

]

story6/models.py
from django.db import models

# Create your models here.

class Orang(models.Model):
    nama = models.CharField(max_length = 30)
    def __str__(self):
        return self.nama
class Event(models.Model):
    nama = models.CharField(max_length =30)
    participants = models.ManyToManyField(Orang)

    def __str__(self):
        return self.nama

story6/forms.py
from django.forms import ModelForm,Form
from .models import Event, Orang
from django import forms

class OrangForm(ModelForm):
    class Meta:
        model = Orang
        fields =[
            'nama'
            ]
        labels = {
            'nama':'Masukan namamu'
        }

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields =['nama']
        label={
            'nama':'Masukan nama acara'
        }
    
    def clean(self):
        super(EventForm, self).clean()
        nama = self.cleaned_data.get('nama')
        for event in Event.objects.all():
            if event.nama == nama:
                self._errors['nama'] = self.error_class(['nama event sudah diambil.... pilih yang baru ya...'])
                return self.cleaned_data
        return self.cleaned_data

story6/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from . import forms
from . import models

# Create your views here.
def event(request):
    response ={
        'event_list':models.Event.objects.all()
    }
    if request.method == 'POST':
        id_number = request.POST.get("id")
        return redirect ('add/'+ id_number)
    return render(request, "event.html", response)

def add(request, id_number):

    event = models.Event.objects.get(id = id_number)
    form = forms.OrangForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        nama = request.POST.get('nama')
        orang = (models.Orang.objects.filter(nama = nama).first() or None)
        if orang:
            event.participants.add(orang)
        else:
            new_orang = models.Orang(nama = nama)
            new_orang.save()
            event.participants.add(new_orang)
        return redirect('/story6/')
    else:
        response ={
            'form':form  
    }
        return render(request, "add_participant.html", response)

def new_event(request):
    form = forms.EventForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        nama = request.POST.get('nama')
        new_event = models.Event(nama = nama)
        new_event.save()
        return redirect('/story6/')
    response ={
        'form':form
    }
    return render(request, "new_event.html", response)

story6/templates/add_participant.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<div class = 'container-fluid'>
    <div class = 'jumbotron'>
    <form method="POST" class="text-left">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
    <p>
        {{status}}
    </p>
    </div>
</div>
{% endblock content %}

story6/templates/event.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<h1 class="text-center">Acara</h1>
<div class="container-fluid">
	<div class="row">
        {% for event in event_list %}
		<div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{event.nama}}
                </div>
                <div class="panel-body">
                    <ol>
                        {% for orang in event.participants.all %}
                        <li class="list-item">
                            {{orang.nama}}
                        </li>
                        {% empty %}
                        <p>belum ada yang join ;-;</p>
                        {% endfor %}
                    </ol>
                    <form method="POST">
                        {% csrf_token %}
                        <input name="tambah" hidden>
                        <input name="id" value="{{event.id}}" hidden>
                        <button type = "submit" class= "btn btn-default"> Tambah partisipan</button>
                    </form>
                </div>  
		    </div>         
        </div>  
            {%endfor%} 
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Mau tambah event mu? silahkan ^^
                </div>
                <div class = 'panel-body'>
                    nanti kalau ada yang join mereka di list disini~
                <a class ="btn btn-default" href="{% url 'story6:add_event' %}">Buat event</a>
                </div>
            </div>       
        </div>
        
	</div>
</div>
{% endblock content %}

story6/templates/new_event.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<div class = 'container-fluid'>
    <div class = 'jumbotron'>
    <form method="POST" class="text-left">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
    <p>
        {{status}}
    </p>
    </div>
</div>
{% endblock content %}