kakPewe4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls'), name ='story3'),
    path('story1/', include('story1.urls'), name = 'story1'),
    path('story4/', include('story4.urls'), name = 'story4'),
    path('story6/', include('story6.urls'), name = 'story6'),
    path('story7/', include('story7.urls'), name = 'story7'),
    path('story8/', include('story8.urls'), name = 'story8'),
    path('story9/', include('story9.urls'), name = 'story9'),

]

story1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutMe/', views.aboutMe, name='about me'),
    path('projects/', views.projects, name='projects'),
    path('experience/',views.experience, name='experience'),
    path('contacts/', views.contacts, name='contacts')
]

story4/urls.py
from django.urls import path, re_path

from . import views

app_name = 'story4'

urlpatterns = [
    path('schedule', views.schedule, name='schedule'),
    path('add/', views.add, name='add'),
    path('manager/', views.manager, name='manager'),
    path('', views.mata_kuliah, name='matkul'),
    path('add_matkul', views.add_matkul,name='add_matkul'),
    path('detil_matkul/<int:item_id>', views.detil_matkul, name="detil_matkul")

]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.event, name='home'),
    path('add/<int:id_number>', views.add, name='add'),
    path('new_event/',views.new_event, name ='add_event')

]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

       
        <style>
            .nav-default{
                  background-color: #F4F9D5;
                  color: #36311F;
              }
          </style>
        {% block title%}
        <title>Kosong eheheh</title>
        {% endblock title%}
        {% block script %}
        <script  src = "{% static 'jquery-ui-1.12.1.custom/external/jquery/jquery.js'%}"></script>
        <script src = "{% static 'jquery-ui-1.12.1.custom/jquery-ui.js'%}"></script>
        
        <link rel = "stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.css'%}">
        {% endblock script %}
        
    </head>
    
    <nav class = "nav nav-default">
        <div class ="container-fluid">
            <ul class = "nav navbar-nav">
            <li><a href="{% url 'story3:home'%}">Home</a></li>
            <li><a href="{% url 'story3:about me'%}">About me</a></li>
            <li><a href="{% url 'story3:projects'%}">Projects</a></li>
            <li><a href="{% url 'story3:experience'%}">Experience</a></li>
            <li><a href="{% url 'story3:contacts'%}">Contact</a></li>
            <li><a href="{% url 'index'%}">Story 1</a></li>
            <li><a href="{% url 'story4:matkul'%}">Story 4</a></li>
            <li><a href="{% url 'story4:schedule'%}">Scheduler</a></li>
            <li><a href="{% url 'story6:home' %}">Story 6</a></li>
            <li><a href="{% url 'story7:index' %}">Story 7</a></li>
            <li><a href="{% url 'story8:index' %}">Story 8</a></li>
            <li><a href="{% url 'story9:index' %}">Story 9</a></li>
            </ul>
            {% if user.is_authenticated %}
            <h5>
                selamat datang {{ user.username }}
            </h5>
            {% endif %}
        </div>
        
    </nav>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>