kakPewe4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls'), name ='story3'),
    path('story1/', include('story1.urls'), name = 'story1'),
    path('story4/', include('story4.urls'), name = 'story4'),
    path('story6/', include('story6.urls'), name = 'story6'),
    path('story7/', include('story7.urls'), name = 'story7'),
    path('story8/', include('story8.urls'), name = 'story8'),
    path('story9/', include('story9.urls'), name = 'story9'),

]

story1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

story4/urls.py
from django.urls import path, re_path

from . import views

app_name = 'story4'

urlpatterns = [
    path('schedule', views.schedule, name='schedule'),
    path('add/', views.add, name='add'),
    path('manager/', views.manager, name='manager'),
    path('', views.mata_kuliah, name='matkul'),
    path('add_matkul', views.add_matkul,name='add_matkul'),
    path('detil_matkul/<int:item_id>', views.detil_matkul, name="detil_matkul")

]

story4/models.py
from django.db import models
from datetime import time
from math import ceil,floor
class Kelas(models.Model):
    HARI =[ (0, "Senin"),
            (1, "Selasa"),
            (2, "Rabu"),
            (3, "Kamis"),
            (4, "Jumat"),
            (6, "Sabtu")
            ]

    nama = models.CharField(max_length=30)
    hari = models.IntegerField(choices=HARI, default="Senin")
    start_time = models.TimeField()
    end_time = models.TimeField()
    bcolor = models.CharField(max_length=30)
    tcolor = models.CharField(max_length=30)

    def calc_length(self, interval):
        total = total_minute(self.end_time)-total_minute(self.start_time)
        return ceil(total/interval)+1

    def calc_period(self, interval, day_start):
        total = total_minute(self.start_time)-total_minute(day_start)
        return floor(total/interval)


class MataKuliah(models.Model):
    nama = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks =  models.CharField(max_length=30)
    deskripsi = models.TextField(default= "monggo diisi")
    semester = models.CharField(max_length=30)
    ruang = models.CharField(max_length=30)

#####################
# utility functions
def total_minute(time):
    return 60*time.hour+time.minute

story4/forms.py
from django.forms import ModelForm,Form
from .models import Kelas, MataKuliah
from django import forms
class KelasForm(ModelForm):
    class Meta:
        model = Kelas
        fields = ['nama','hari','start_time', 'end_time', 'bcolor','tcolor']
        labels = {
            "nama": "Nama Kelas",
            "start_time":"Awal Kelas",
            "end_time":"Akhir Kelas",
            "bcolor":"Warna Background Kelas",
            "hari":"hari",
            "tcolor":"warna text",
        }
      
    def clean(self):
        super(KelasForm,self).clean()

        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')
        hari = self.cleaned_data.get('hari')
        if(start_time == None):
            self._errors['start_time'] = self.error_class(['format waktu tidak valid, gunakan HH:MM'])
            return self.cleaned_data
        if (end_time == None):
            self._errors['end_time'] = self.error_class(['format waktu tidak valid, gunakan HH:MM'])
            return self.cleaned_data
        minute_start =total_minute(start_time)
        minute_end = total_minute(end_time)
        if total_minute(end_time)<total_minute(start_time):
            self._errors['start_time'] = self.error_class(['waktu akhir lebih dulu dari waktu awal'])
            self._errors['end_time'] = self.error_class(['waktu akhir lebih dulu dari waktu awal'])
            return self.cleaned_data
        
        for kelas in Kelas.objects.all():
            if kelas.hari == hari and (total_minute(kelas.end_time) >= minute_start and total_minute(kelas.start_time)<=minute_end):                    
                self._errors['start_time'] = self.error_class(['ada overlap kelas'])
                self._errors['end_time'] = self.error_class(['ada overlap kelas'])
                return self.cleaned_data
        return self.cleaned_data
        

class MatkulForm(ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'nama', 'dosen', 'sks', 'semester', 'ruang', 'deskripsi'
        ]
        labels = {
            'nama':'nama Mata Kuliah',
            'dosen':'Dosen Pengajar',
            'sks':'Jumlah SKS',
            'semester':'Semester',
            'ruang':'Ruang',
            'deskripsi':'Deskripsi kelas',
        }


###############################################
#utility functions
def total_minute(time):
    return time.hour*60+time.minute

story4/views.py
from django.shortcuts import render, redirect
from datetime import datetime, timedelta, time, date
from . import models
from .forms import KelasForm, MatkulForm
start_time = "08:00"
end_time = "18:30"
interval = 30



# Create your views here.
def schedule(request):
    kelas_list = models.Kelas.objects.all()
    response={
            "schedule_table":create_event_table(kelas_list,interval,start_time,end_time)
    }           
    return render(request, 'table.html', response)

def add(request):
    form = KelasForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return render(request, 'add_new.html', {"form": form, "status":"Berhasil menambahkan kelas baru, silahkan cek Scheduler ^^"})
    else:
        return render(request, 'add_new.html', {"form": form, "status":""})
    
    
def manager(request):
    response = {
        'kelas_list':create_kelas_list(models.Kelas.objects.all())
    }
    
    id_number = request.POST.get("id")
    
    if "delete" in request.POST and  request.method == 'POST':
        kelas_instance = models.Kelas.objects.get(id=id_number)
        kelas_instance.delete()
        response = {
        'kelas_list':create_kelas_list(models.Kelas.objects.all())
        } 
        return render(request, "manager.html", response)  
    return render(request, "manager.html", response)

def mata_kuliah(request):
    mata_kuliah_list=models.MataKuliah.objects.all()
    response = {
        "matkul_list":mata_kuliah_list
    }
    id_number = request.POST.get("id")
    
    if "delete" in request.POST:
        matkul_instance = models.MataKuliah.objects.get(id=id_number)
        matkul_instance.delete()
        response = {
        'matkul_list':models.MataKuliah.objects.all()
        } 
    if "detail" in request.POST:
        return redirect('detil_matkul/'+id_number)
    return render(request, "mata_kuliah.html", response)

def add_matkul(request):
    form = MatkulForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return render(request, 'add_matkul.html', {"form": form, "status":"Berhasil menambahkan matkul baru, silahkan cek halaman Story 4 ^^"})
    else:
        return render(request, 'add_matkul.html', {"form": form, "status":""})


def detil_matkul(request, item_id):
    matkul_instance = models.MataKuliah.objects.get(id=item_id)
    return render(request, 'detil_matkul.html',{'matkul':matkul_instance})

##########################################################################


# Utility functions
def  create_time_table(start_time, end_time,interval):
    current = datetime.combine(date.min,time.fromisoformat(start_time))
    end = datetime.combine(date.min,time.fromisoformat(end_time))
    time_list =[current.strftime("%H:%M")]
    while current < end:
        current += timedelta(minutes=interval)
        time_list.append(current.strftime("%H:%M"))
    return time_list

def create_event_table(kelas_list, interval, start_time,end_time):
    time_list = create_time_table(start_time,end_time,interval)
    schedule_table = []
    for i in range(len(time_list)):
        schedule_table.append([{"row":1,"content":time_list[i]}])
        for j in range(6):
            schedule_table[i].append({"row":1,"content":""})
    for kelas in kelas_list:
        schedule_table[kelas.calc_period(interval,time.fromisoformat(start_time))][kelas.hari+1]=(
            {"row":kelas.calc_length(interval),"content":  kelas.nama, "bcolor":kelas.bcolor,
            "tcolor":kelas.tcolor,})
    return schedule_table

def create_kelas_list(kelas_list):
    HARI ={ 
        0: "Senin",
        1: "Selasa",
        2: "Rabu",
        3: "Kamis",
        4: "Jumat",
        6: "Sabtu"
    }
    readable_list = []
    for kelas in kelas_list:
        kelas_dict ={}
        kelas_dict["nama"] = kelas.nama
        kelas_dict["hari"] = HARI[kelas.hari]
        kelas_dict["start_time"] =kelas.start_time.strftime("%H:%M")
        kelas_dict["end_time"] =kelas.end_time.strftime("%H:%M")
        kelas_dict["bcolor"] = kelas.bcolor
        kelas_dict["tcolor"] = kelas.tcolor
        kelas_dict["id"] = kelas.id
        readable_list.append(kelas_dict)
    return readable_list

story4/templates/add_matkul.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<div>
    <form method="POST" class="text-left">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input type="submit" value="submit">
    </form>
    <p>
        {{status}}
    </p>
</div>
{% endblock content %}

story4/templates/add_new.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<div>
    <form method="POST" class="text-left">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input type="submit" value="submit">
    </form>
    <p>
        {{status}}
    </p>
</div>
{% endblock content %}

story4/templates/detil_matkul.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<table class = "table table-striped">
    <tbody>
      <tr>
        <td style="width: 1%;">Nama</td>
        <td>{{matkul.nama}}</td>
      </tr>
      <tr>
        <td>Dosen</td>
        <td>{{matkul.dosen}}</td>
      </tr>
      <tr>
        <td>SKS</td>
        <td>{{matkul.sks}}</td>
      </tr>
      <tr>
        <td>Semester</td>
        <td>{{matkul.semester}}</td>
      </tr>
      <tr>
        <td>Ruang</td>
        <td>{{matkul.ruang}}</td>
      </tr>
      <tr>
        <td>Deskripsi</td>
        <td>{{matkul.deskripsi}}</td>
      </tr>
    </tbody>
    </table>
{% endblock content %}

story4/templates/manager.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<a class ="btn btn-default" href="{% url 'story4:add_matkul' %}">Tambahkan kelas</a>
<table class = "table table-bordered">
    <thead>
      <tr>
        <th style="width: 1%;">No</th>
        <th class="text-center">Nama Kelas</th>
        <th class="text-center">Hari</th>
        <th class="text-center">Kelas mulai</th>
        <th class="text-center">Kelas habis</th>
        <th class="text-center">Warna Background</th>
        <th class="text-center">Warna Text</th>
      </tr>
    </thead>
    <tbody>
        {% for kelas in kelas_list %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{kelas.nama}}</td>
            <td>{{kelas.hari}}</td>
            <td>{{kelas.start_time}}</td>
            <td>{{kelas.end_time}}</td>
            <td>{{kelas.bcolor}}</td>
            <td>{{kelas.tcolor}}</td>
            <td>
                <form method="POST">
                    {% csrf_token %}
                    <input name="delete" hidden>
                    <input name="id" value="{{kelas.id}}" hidden>
                    <button type = "submit" class= "btn btn-default"> delete</button>
                </form>           
            </td>
        </tr>
        {% empty %}
        Kamu belum memasukan kelas apapun  jadi masih kosong :(
        {% endfor %}
    </tbody>
{% endblock content %}

story4/templates/mata_kuliah.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %} 
{% bootstrap_messages %}
{% block content %}
<a class ="btn btn-default" href="{% url 'story4:add_matkul' %}">Tambahkan kelas</a>
<table class = "table table-bordered">
    <thead>
      <tr>
        <th style="width: 1%;">No</th>
        <th class="text-center">Nama Matkul</th>
        <th class="text-center">Dosen</th>
        <th class="text-center">SKS</th>
        <th class="text-center">Semester</th>
        <th class="text-center">Ruang</th>
      </tr>
    </thead>
    <tbody>
        {% for matkul in matkul_list %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{matkul.nama}}</td>
            <td>{{matkul.dosen}}</td>
            <td>{{matkul.sks}}</td>
            <td>{{matkul.semester}}</td>
            <td>{{matkul.ruang}}</td>
            <td>
                <form method="POST">
                    {% csrf_token %}
                    <input name="delete" hidden>
                    <input name="id" value="{{matkul.id}}" hidden>
                    <button type = "submit" class= "btn btn-default"> delete</button>
                </form>           
            </td>
            <td>
                <form method="POST">
                    {% csrf_token %}
                    <input name="detail" hidden>
                    <input name="id" value="{{matkul.id}}" hidden>
                    <button type = "submit" class= "btn btn-default"> detail</button>
                </form>           
            </td>
        </tr>
        {% empty %}
        Kamu belum memasukan mata kuliah apapun  jadi masih kosong :(
        {% endfor %}  
{% endblock content %}

story4/templates/table.html
{% extends 'base.html' %}
{% load static %}
{%block title %}
<title> Schedule </title>
{% endblock title%}
{% block content %}
<a class ="btn btn-default" href="{% url 'story4:add' %}">Tambahkan kelas</a>
<a class ="btn btn-default" href="{%url 'story4:manager' %}">Edit/Hapus kelas</a>
<table class = "table table-striped">
    <thead>
      <tr>
        <th style="width: 1%;">Jam</th>
        <th class="text-center">Senin</th>
        <th class="text-center">Selasa</th>
        <th class="text-center">Rabu</th>
        <th class="text-center">Kamis</th>
        <th class="text-center">Jumat</th>
        <th class="text-center">Sabtu</th>
      </tr>
    </thead>
    <tbody>
      {% for weekly in schedule_table %}
      <tr>
        {% for daily in weekly%}
        <td rowspan="{{daily.row}}" class = "text-center" style="background-color: {{daily.bcolor}}; color: {{daily.tcolor}};">
          {{daily.content}}
        </td>
        {% endfor %}
      {% endfor %}
    </tbody>
    </table>
{% endblock content %}